server:
  port: ${SERVER_PORT}
spring:
  application:
    name: club-card-auth-service
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
springdoc:
  swagger-ui:
    url: openapi/auth-service-specification.yml
security:
  jwt:
    secret-key: ${SECRET_KEY}
    expiration-time: ${EXPIRATION_TIME}
    expiration-time-refresh: ${EXPIRATION_TIME_REFRESH}